language: python
branches:
  only:
    - master
    - next
    - pingudev
python:
  - "2.7"
sudo: false
install:
  - make install
  - make start
before_script:
  - sleep 10
script:
  - export GDAL_DATA=/home/travis/.conda/envs/flyingpigeon/share/gdal 
#  - make docs
  - make testall
#after_success:
# - coveralls
