name: flyingpigeon
channels:
- conda-forge
- defaults
- birdhouse
# ocgis
- nesii
# the r hell ...
- r
- bioconda
dependencies:
- python=2.7.12=1  #  conda-forge
- ipython=5.1.0 
- gcc# =4.8.5
- pyopenssl# =0.16.0
- cryptography=1.5.2=py27_0 #- cryptography=1.5.2
- psutil
- cffi=1.8.3=py27_0
- setuptools=27.2.0
- icu=58 #  conda-forge
- libxslt#=1.1.28
################
# tests
- pytest
- flake8
################
# docs
- sphinx
- sphinx_rtd_theme
################
# wps
- nginx # =1.10.1
- supervisor # =3.3.1
- gunicorn # =19.1.0
- gevent
- pywps=3.2.6=py27_1 
- mako
################
# misc
- pywget
- pyyaml=3.12
################
# numeric
- numpy
- scipy 
- pandas #=0.18.1
- statsmodels #=0.6.1
- scikit-learn #=0.17.1 
# cartopy
- cartopy #=0.14.2 # conflicts with numpy >1.10
- iris #=1.9.2 # conflicts with numpy >1.10
################
## cdo ocgis 
- cdo #=1.7.1=2
- python-cdo
- ocgis-next=1.4.0.dev1=py27_3  #  nesii/channel/ocgis-next
- proj.4=4.9.2
- geos=3.4.2
- jpeg=9b
################
# analogue
- castf90=0.1.5
################
# r
- cairo # for X11 independend plot support 
- r=3.2  # 3.3 conflicts with icu=56
- rpy2 #=2.7.0
- r-mclust #=5.1 subsuituted by cluster
- r-ncdf4=1.15=1
- r-fields #=8.4 conflicts with r3.3.1 needs 3.2
- r-gridextra #=2.0.0
- harfbuzz=0.9.39
#- r-cairo#=1.5_9 build in r-base
- pip:
  - genshi==0.7
  - pygbif==0.2.0 #0.1.4
  - sphinx-autoapi==0.4.0
#  - cdo==1.3.0
